export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
export const SET_LIST_PACKAGES = "SET_LIST_PACKAGES";
export const SET_COUNT_PACKAGES_PAGES = "SET_COUNT_PACKAGES_PAGES";
export const CLEAR_SEARCH = "CLEAR_SEARCH";